#!/bin/bash

BOOKMARKS_PATH=~/.config/BraveSoftware/Brave-Browser/Default/Bookmarks
BACKUP_ROOT_PATH=./backups
SECONDS_IN_A_DAY=86400

suffix=`date +%m%d%y_%H%M%S`
fileName=Bookmarks_${suffix}.json
backupFilePath=$BACKUP_ROOT_PATH/$fileName
runType=force

copy_bookmarks() {
    cp $BOOKMARKS_PATH $backupFilePath
}

check_mtime() {
    bookmarkTime=`stat -c %Y $BOOKMARKS_PATH`
    currentTime=`date +%s`
    timeDifference=`expr $currentTime - $bookmarkTime`
 
    if [ $timeDifference -lt $SECONDS_IN_A_DAY ]; then
        copy_bookmarks
        push_backup
    fi
}

push_backup() {
    commitMessage="Backup: `date "+%b %d, %Y"`"

    git add $backupFilePath
    git commit -m "$commitMessage"
    git push
}

usage() {
    echo "usage: backup [run-type]"
    echo "    run-type: force, day (default: force)"
}

if [ "$#" -gt 1 ]; then
    echo "error: to many peremeters"
    usage
    exit 1
fi

if [ -n "$1" ]; then
    runType=$1
fi

if [ $runType == "force" ]; then
    copy_bookmarks
elif [ $runType == "day" ]; then
    check_mtime
else
    echo "error: invalid run-type: $runType"
    usage
    exit 1
fi

